### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by scratcher28** [PhiloNL/artisan-remote#3]
I am running my laravel app in Docker. So, my commands looks like: 
`docker-compose exec -T apache bash -c "cd /src && php artisan backup:run --only-db"`
Could you please make artisan-remote more flexible? It could be a command template or so.
For example: `docker-compose exec -T apache bash -c "cd /src && %%ARTISAN_COMMAND_PLACEHOLDER%%"`.

**Comment by PhiloNL** [comment]
Hi @scratcher28 

Artisan remote doesn't support SSH commands at the moment, but it should work with Docker if your Laravel application is reachable via HTTP(s).

Install the `artisan-remote` package (`composer require philo/artisan-remote`) and follow the [configuration guide](https://github.com/PhiloNL/artisan-remote/blob/master/README.md).

You can now use the API locally via `http://localhost`. If you are using the desktop app, you can just enter the localhost URL. If you expose the backup command in the configuration, you can invoke the command with the `--only-db` flag.
